config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/dashboard', to: "dashboard#index", as: :dashboard
  get '/current', to: 'dashboard#my_tasks', as: :current

  get '/workflows', to: 'workflows#search', as: :workflows

  resources :workflows, only: [:create, :show, :update, :destroy] do
    resources :tasks, only: [:index, :show]
    member do
      get :completion
      get :reset
    end
  end

  put '/activate', to: 'workflows#activate', as: :activate

  get '/tasks', to: 'tasks#search', as: :tasks

  resources :tasks, only: [:index, :new, :create, :destroy, :update] do
    resources :items, only: [:new]
    resources :task_members, only: [:create, :new, :destroy]
    member do
      get :complete_task
      get :complete_mytask
      get :show_mytask
    end
    get :email_notification, to: "notifications#email_notification"
  end

  resources :items, only: [:index, :create, :show, :destroy, :update] do
    member do
      patch :move
      patch :move_repo
      get :expand
      get :check
    end
  end



end

app/views/my_tasks/_completed_content.html.erb
<%= render partial: 'my_tasks/my_task_header', locals: { task: task } %>

<%# Content inside here %>
<div class="p-4 flex flex-col justify-between border shadow-lg rounded-lg">

  <div class="flex items-center pb-4">
    <svg class="mr-4" xmlns="http://www.w3.org/2000/svg" width="13" height="15" viewBox="0 0 14 16">
      <path id="paper_1" d="M266,416h-7a2.006,2.006,0,0,0-2,2v12a2.006,2.006,0,0,0,2,2h10a2.006,2.006,0,0,0,2-2v-9A5,5,0,0,0,266,416Zm3,14H259V418h5v5h5Zm-3-9v-3a3.009,3.009,0,0,1,3,3Z" transform="translate(-257 -416)"/>
    </svg>
    <div class="text-lg font-medium"><%= task.title %></div>
  </div>
  <div class="text-sm pb-4 text-gray-500"><%= task.description %></div>

  <div class="flex">

    <%# Items Section %>
    <div class="flex-grow pr-4">
      <ul class="shadow-inner t-item-box flex-grow bg-gray-100 rounded-lg px-2 pb-1" data-item-target="list" data-controller="drag" data-drag-url="/items/:id/move" data-task-id=<%= task.id %>>

        <div class="text-xs text-gray-300 pt-2 text-center">Drop items here</div>
        <%= render partial: 'items/items', locals: { items: task.items, workflow: task.workflow, task: task  } %>

      </ul>
    </div>

    <%# Members Section %>
    <div class="border-l w-40 px-3 pt-2">
      <ul>
        <%= render partial: 'tasks/task_members', locals: {task_members: task.users, task: task} %>
      </ul>
    </div>

  </div>

</div>

<%# dotted line connector %>
<div class="t-connector h-14"></div>



<%# next task %>
<% if next_task %>
  <%= render partial: 'my_tasks/next_task_header', locals: { task: next_task } %>

  <div class="p-4 shadow-lg rounded-lg border">

    <div class="flex items-center pb-4">
      <svg class="mr-4" xmlns="http://www.w3.org/2000/svg" width="13" height="15" viewBox="0 0 14 16">
        <path id="paper_1" d="M266,416h-7a2.006,2.006,0,0,0-2,2v12a2.006,2.006,0,0,0,2,2h10a2.006,2.006,0,0,0,2-2v-9A5,5,0,0,0,266,416Zm3,14H259V418h5v5h5Zm-3-9v-3a3.009,3.009,0,0,1,3,3Z" transform="translate(-257 -416)"/>
      </svg>
      <div class="text-lg font-medium"><%= next_task.title %></div>
    </div>
    <div class="text-sm pb-4 text-gray-500"><%= next_task.description %></div>

  <%# nexttask - Items section %>
    <div class="pr-4 flex">
      <ul class="flex-grow pr-4" >

        <%= render partial: 'items/items', locals: { items: next_task.items, workflow: next_task.workflow, task: next_task  } %>

      </ul>
      <%# nexttask - Members Section %>
      <div class="border-l w-40 px-3 pt-2">
        <ul>
          <%= render partial: 'tasks/task_members', locals: {task_members: next_task.users, task: next_task} %>
        </ul>
      </div>
    </div>

  </div>

<% else %>
  <div class="flex justify-center">
    <div class="text-sm py-2 px-4 bg-gray-100 text-gray-400 rounded-md">End of Workflow</div>
  </div>
<% end %>

app/views/my_tasks/_my_task_content.html.erb
<%# Title and status %>
<%= render partial: 'my_tasks/my_task_header', locals: { task: task } %>

<%# My Tasks content %>
<% if task.workflow.activated? %>
<%# Content inside here %>
  <div data-controller="toggle" class="relative container p-4 flex flex-col justify-between border shadow-lg rounded-lg"
       data-task-id=<%= task.id %> data-workflow-id=<%= task.workflow.id %>>

    <%# Description %>
    <div class="flex items-center pb-4">
      <svg class="mr-4" xmlns="http://www.w3.org/2000/svg" width="13" height="15" viewBox="0 0 14 16">
        <path id="paper_1" d="M266,416h-7a2.006,2.006,0,0,0-2,2v12a2.006,2.006,0,0,0,2,2h10a2.006,2.006,0,0,0,2-2v-9A5,5,0,0,0,266,416Zm3,14H259V418h5v5h5Zm-3-9v-3a3.009,3.009,0,0,1,3,3Z" transform="translate(-257 -416)"/>
      </svg>
      <div class="text-lg font-medium"><%= task.title %></div>
    </div>

    <div class="text-sm pb-4 text-gray-500"><%= task.description %></div>

    <div class="flex pb-4">

      <%# Items Section %>
      <div class="flex-grow pr-4">
        <ul class="shadow-inner t-item-box flex-grow bg-gray-100 rounded-lg px-2 pb-1" data-item-target="list" data-controller="drag" data-drag-url="/items/:id/move" data-task-id=<%= task.id %>>
          <div class="text-xs text-gray-300 pt-2 text-center">Drop items here</div>

          <%= render partial: 'items/items', locals: { items: task.items, workflow: @workflow, task: @task  } %>

        </ul>
      </div>

      <%# Members Section %>
      <div class="border-l w-40 px-3">
        <ul class="flex-grow">
          <%= render partial: 'tasks/task_members', locals: {task_members: task.users, task: task} %>
        </ul>
      </div>

    </div>
    <% if task.current? %>
      <%= link_to 'Complete Task', complete_mytask_task_path(task), class: "t-btn-outline text-sm justify-center" %>
    <% end %>

    <% if task.current? %>
      <button class="t-btn-square border absolute top-3 -right-3 bg-white flex items-center justify-center" data-action="click->notification#sendemail">
        <i class="far fa-envelope text-sm text-black"></i>
      </button>
    <% end %>
  </div>

  <%# dotted line connector %>
  <div class="t-connector h-14"></div>



  <%# next task %>
  <% if next_task %>
    <%= render partial: 'my_tasks/next_task_header', locals: { task: next_task } %>

    <div data-controller="toggle item" data-task-id=<%= next_task.id %> class="p-4 shadow-lg rounded-lg border">

      <div class="flex items-center pb-4">
        <svg class="mr-4" xmlns="http://www.w3.org/2000/svg" width="13" height="15" viewBox="0 0 14 16">
          <path id="paper_1" d="M266,416h-7a2.006,2.006,0,0,0-2,2v12a2.006,2.006,0,0,0,2,2h10a2.006,2.006,0,0,0,2-2v-9A5,5,0,0,0,266,416Zm3,14H259V418h5v5h5Zm-3-9v-3a3.009,3.009,0,0,1,3,3Z" transform="translate(-257 -416)"/>
        </svg>
        <div class="text-lg font-medium"><%= next_task.title %></div>
      </div>
      <div class="text-sm pb-4 text-gray-500"><%= next_task.description %></div>
      <div class="flex pb-4">
    <%# nexttask - Items section %>
        <div class="flex-grow pr-4 flex flex-col">
          <ul class="shadow-inner t-item-box flex-grow bg-gray-100 rounded-lg px-2 pb-1" data-item-target="list" data-controller="drag" data-drag-url="/items/:id/move" data-task-id=<%= next_task.id %>>

            <div class="text-xs text-gray-300 pt-2 text-center">Drop items here</div>
            <%= render partial: 'items/items', locals: { items: next_task.items, workflow: next_task.workflow, task: next_task  } %>

          </ul>

          <%= render partial: 'items/itemadd', locals: {task: next_task} %>
        </div>

      <%# nexttask - Members Section %>
        <div class="border-l w-40 px-3 flex flex-col">

          <ul data-toggle-target="taskmemberslist" class="flex-grow">
            <%= render partial: 'tasks/task_members', locals: {task_members: next_task.users, task: next_task} %>
          </ul>

          <%= render partial: 'members/add_member', locals: {task: next_task} %>
        </div>
      </div>
    <%# flex end %>
    </div>


  <% else %>
    <div class="flex justify-center">
      <div class="text-sm py-2 px-4 bg-gray-100 text-gray-400 rounded-md">End of Workflow</div>
    </div>
  <% end %>

<% else %>
  This task is currently not active.
<% end %>

app/views/my_tasks/_my_task_header.html.erb
<%# Title %>

<div class="container flex flex-wrap items-center gap-2 mb-3">

  <% unless task.completed? %>
    <div class="shadow-md rounded-md py-1 px-2 text-sm">
      <i class="fas fa-circle text-xs text-indigo-400"></i>
      &nbsp;Current
    </div>
  <% else %>
   <div class="shadow-md rounded-md py-1 px-2 text-sm">
      <i class="fas fa-circle text-xs text-green-400"></i>
      &nbsp;Completed
    </div>
  <% end %>
</div>

app/views/my_tasks/_my_tasks_l.html.erb
<div data-controller="sidebar-l">

  <%# create button %>
  <button data-action="click->sidebar-l#createBtnDropdown" class="t-btn-outline mt-5">
      <svg class="t-hover-white mx-2" xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10">
        <path id="mini_plus" d="M44,743H41v-3a1,1,0,0,0-2,0v3H36a1,1,0,0,0,0,2h3v3a1,1,0,0,0,2,0v-3h3a1,1,0,0,0,0-2Z" transform="translate(-35 -739)"/>
      </svg>
    <h5 class="text-sm">Create</h5>
  </button>

  <%# create button dropdown %>
  <div data-sidebar-l-target="dropdownCreate" class="t-dropdown w-48 hidden">
    <%= link_to 'Workflow', workflows_path, method: 'post',
    class: "t-dropdown-btn" %>
  </div>

  <%# tab %>
  <div class="flex gap-4 my-5">
    <%= link_to "My Tasks #{ "(#{current_user.my_tasks.length})" unless current_user.my_tasks.empty?}", current_path, class: 't-tab-active' %>
    <%= link_to 'Workflows', dashboard_path, class: 't-tab' %>
  </div>

  <%# search bar form to search within tab %>
  <%= form_with url: tasks_path, class: "text-light", method: :get do |f| %>

    <div class="search-bar rounded-t-lg">
      <button type="submit" class="input-l">
        <i class="fas fa-search"></i>
      </button>

      <%= f.text_field :query, class: "t-input-invis flex-grow pl-3 bg-gray-700", placeholder: "Tasks" %>
    </div>

  <% end %>

  <%# task tabs list %>
  <div class="mt-4 h-96 overflow-scroll">

    <div class="text-gray-100 border-b border-indigo-400 pb-1 mb-3">To do</div>
    <%= render 'my_tasks/tasks_tabs', tasks: @my_tasks %>

    <div class="text-gray-100 border-b border-indigo-400 pb-1 mt-6 mb-3">Completed</div>
    <%= render 'my_tasks/tasks_tabs', tasks: @completed_tasks %>
  </div>

</div>

app/views/my_tasks/_next_task_header.html.erb
<%# Title %>

<div class="container flex flex-wrap items-center gap-2 mb-3">

  <% unless task.completed? %>
    <div class="shadow-md rounded-md py-1 px-2 text-sm">
      <i class="fas fa-circle text-xs text-gray-200"></i>
      &nbsp;Next task
    </div>
  <% else %>
   <div class="shadow-md rounded-md py-1 px-2 text-sm">
      <i class="fas fa-circle text-xs text-green-400"></i>
      &nbsp;Completed
    </div>
  <% end %>

</div>

app/views/my_tasks/_tasks_tabs.html.erb
<% tasks.each do |task| %>

  <% if task == @task %>
    <div data-controller="sidetabs" data-task-id=<%= task.id %> class="t-sidetab-btn-active flex items-center justify-between shadow-md">
  <% else %>
    <div data-controller="sidetabs" data-task-id=<%= task.id %> class="t-sidetab-btn flex items-center justify-between">
  <% end %>

    <div class="mr-3">
      <svg xmlns="http://www.w3.org/2000/svg" width="13" height="15" viewBox="0 0 14 16">
        <path id="paper_1" d="M266,416h-7a2.006,2.006,0,0,0-2,2v12a2.006,2.006,0,0,0,2,2h10a2.006,2.006,0,0,0,2-2v-9A5,5,0,0,0,266,416Zm3,14H259V418h5v5h5Zm-3-9v-3a3.009,3.009,0,0,1,3,3Z" transform="translate(-257 -416)"/>
      </svg>
    </div>

    <a class="flex-grow cursor-pointer" data-action="click->sidetabs#selectMyTask">
      <%= task.title %>
    </a>

  </div>

<% end %>

app/views/my_tasks/index.html.erb
<div class="flex">

  <div class="w-72 p-5 shadow-lg fixed h-screen bg-gray-800 rounded-r-xl">
    <%= link_to current_path, class: 'h-6' do %>
      <%= image_tag 'Taskete_logo_white.png', class: 'h-6' %>
    <% end %>
    <%= render "my_tasks/my_tasks_l" %>
  </div>
  <%# <div class="w-72"></div> ghost sidebar to push content %>


  <div class="main-content w-3/4 pt-4 pl-10">
    <div id="mytask-content">
      <% if @task %>
        <%= render partial: 'my_tasks/my_task_content', locals: { task: @task, next_task: @next_task } %>
      <% end %>

    </div>
  </div>


  <div class="w-1/4 pt-2 px-5">
    <%= render 'shared/sidebar_r' %>
  </div>

</div>