config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/dashboard', to: "dashboard#index", as: :dashboard
  get '/current', to: 'dashboard#my_tasks', as: :current

  get '/workflows', to: 'workflows#search', as: :workflows

  resources :workflows, only: [:create, :show, :update, :destroy] do
    resources :tasks, only: [:index, :show]
    member do
      get :completion
      get :reset
    end
  end

  put '/activate', to: 'workflows#activate', as: :activate

  get '/tasks', to: 'tasks#search', as: :tasks

  resources :tasks, only: [:index, :new, :create, :destroy, :update] do
    resources :items, only: [:new]
    resources :task_members, only: [:create, :new, :destroy]
    member do
      get :complete_task
      get :complete_mytask
      get :show_mytask
    end
    get :email_notification, to: "notifications#email_notification"
  end

  resources :items, only: [:index, :create, :show, :destroy, :update] do
    member do
      patch :move
      patch :move_repo
      get :expand
      get :check
    end
  end



end

app/models/workflow.rb
class Workflow < ApplicationRecord
  # after_commit :async_update
  validates :title, presence: true

  belongs_to :creator, class_name: "User"

  has_many :tasks, dependent: :destroy

  has_many :items, through: :tasks

  def activated?
    self.activated
  end

  def activate
    self.update(activated: true)
  end

  def deactivate
    self.update(activated: false)
  end

  def completed?
    self.completed
  end

  def complete
    self.update(completed: true)
  end

  def uncomplete
    self.update(completed: false)
  end

  # def async_update
  #   UpdateWorkflowJob.perform_later(self)
  # end
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  before_action :set_workflows_and_task, only:[:create, :show, :update, :activate, :reset]
  before_action :set_workflow, only: [:show, :update, :completion, :destroy, :reset]

  def create
    title_check = Workflow.where(title: 'New Workflow')
    title = title_check[0] ? "#{title_check[0].title} copy" : 'New Workflow'

    new_workflow = Workflow.new(title: title)
    new_workflow.creator = current_user
    new_workflow.save

    respond_to do |format|
      format.html { redirect_to workflow_path(new_workflow) }
      format.text { render partial: 'shared/workflow_tab', locals: { workflow: new_workflow }, formats: [:html] }
    end
  end

  def show
    respond_to do |format|
      format.html { render 'dashboard/index' }
    end
  end

  def search
    sql_query = " \
        workflows.title @@ :query \
        "
        # OR workflows.user.first_name @@ :query \
        # OR workflows.user.last_name @@ :query \

    if params[:query] == ''
      @workflows = Workflow.all
    else
      @workflows = Workflow.where(sql_query, query: "%#{params[:query]}%")
    end

    render 'dashboard/index'
  end

  def update
    @workflow = Workflow.find(params[:id])
    @workflow.update(restful_workflow_params) # updates title

    render 'dashboard/index'
  end

  def activate
    workflow_params = JSON.parse(request.body.read)
    @workflow = Workflow.find(workflow_params['workflowId'])
    if @workflow.activated?
      @workflow.deactivate
    else
      @workflow.activate
      update_first_task_as_current(@workflow)
    end

    respond_to do |format|
      # format.text { render 'dashboard/index', formats: [:html] }
      format.text { render partial: 'workflows/workflow_content', locals: { workflow: @workflow }, formats: [:html] }
    end
  end

  def completion
    respond_to do |format|
      format.text { render partial: 'workflows/workflow_status', locals: { workflow: @workflow }, formats: [:html] }
    end
    # not returning the correct status
  end

  def destroy
    @workflow.destroy unless @workflow.activated?

    redirect_to dashboard_path
  end

  def reset
    @workflow.tasks.each do |task|
      task.update(completed: "pending")
    end
    @workflow.uncomplete

    render 'dashboard/index'
  end

  private

  def restful_workflow_params
    params.require(:workflow).permit(:title)
  end

  def set_workflow
    @workflow = Workflow.find(params[:id])
  end

  def set_workflows_and_task
    @workflows = Workflow.where(creator_id: current_user.id).reverse_order
    @task = Task.new
  end

  def update_first_task_as_current(workflow)

    workflow.tasks.each do |task|
      if task.completed? && task.lower_item.nil?
        workflow.complete
      elsif task.first? && !task.completed?
        task.set_current
        workflow.uncomplete
      elsif !task.completed?
        workflow.uncomplete
        unless task.higher_item.nil?
          task.set_current if task.higher_item.completed?
        end
      end
    end
  end
end

app/helpers/workflows_helper.rb
module WorkflowsHelper
end

app/views/workflows/_workflow_content.html.erb
<%= render partial: 'workflows/workflow_header' %>
<%# Workflow content %>

<div class="t-workflow-content flex-grow flex flex-col justify-between border border-gray-200 rounded-lg bg-gray-50">

  <div class="px-4 py-1 bg-indigo-200 text-xs text-white rounded-t-md">
    Start
  </div>


  <% if @workflow %>
  <%# Content inside here %>
    <div class="flex-grow px-1">
      <div data-controller="task" data-workflow-id=<%= @workflow.id%> class="my-5 flex flex-col justify-center">

        <div data-task-target="taskslist">
        </div>

        <div data-task-target="newform">
        </div>

        <% unless @workflow.activated? %>
          <%= render "tasks/taskadd", locals: {workflow: @workflow}%>
        <% else %>
          <div class="flex justify-center">
            <div class="mx-6 my-2 rounded-lg flex items-center px-4 py-2 text-xs text-gray-400 bg-gray-100">
              Complete <%= @workflow.tasks.where(completed: 'completed').length %>/<%= @workflow.tasks.length %>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  <% end %>

  <div class="px-4 py-1 bg-indigo-200 text-xs text-white rounded-b-md">
    End
  </div>

</div>

app/views/workflows/_workflow_header.html.erb
<%# Title %>
<% if @workflow %>
  <div data-item-id=<%= @workflow.id%> class="flex justify-between items-center mb-3">
    <div class="flex items-center gap-2">

      <svg class="ml-4" xmlns="http://www.w3.org/2000/svg" width="16" height="14" viewBox="0 0 16 14">
        <path id="folder_1" d="M334,451h-4.764l-.447-.895A2,2,0,0,0,327,449h-5a2,2,0,0,0-2,2v10a2,2,0,0,0,2,2h12a2,2,0,0,0,2-2v-8A2,2,0,0,0,334,451Zm-7,0,1,2h6v1H324a1,1,0,0,0-.949.683L322,457.837V451Zm7,10H323.054l1.667-5H334Z" transform="translate(-320 -449)"/>
      </svg>
      <% if @workflow.activated? %>
        <div class="text-lg font-medium rounded-lg py-2 px-2">
          <%= @workflow.title %>
        </div>
        <%= render partial: 'workflows/workflow_status', locals: {workflow: @workflow} %>

      <% else %>
        <div class="relative">
        <%= simple_form_for @workflow, method: 'PUT' do |f| %>
        <%= f.input :title,
                    label: false,
                    input_html: {class: "group relative text-lg font-medium rounded-lg py-2 px-4 outline-none focus:bg-white focus:ring-1 focus:ring-indigo-600",
                                 autocomplete: "off"
                    },
                    autofocus: true,
                    data: { 'workflow-target': 'form'} %>
        <% end %>
                    <span class="absolute right-2 inset-y-0 flex items-center pl-3">
              <!-- Heroicon name: solid/lock-closed -->

              <svg class="h-4 w-4 fill-current text-gray-300 "xmlns="http://www.w3.org/2000/svg" width="15.984" height="16" viewBox="0 0 15.984 16">
                <path id="pen_1" d="M34.006,432a2,2,0,0,1-2-2v-2a2,2,0,0,1,.585-1.415l9.99-10a2,2,0,0,1,2.826,0l2,2a2,2,0,0,1,0,2.828l-9.99,10A2,2,0,0,1,36,432Zm0-4v2h2l7.786-7.794-2-2Zm11.2-7.207.792-.793-2-2-.792.793Z" transform="translate(-32.008 -416)"/>
              </svg>
            </span>
          </div>
        <div class="rounded-md bg-gray-100 py-1 px-2 text-sm text-gray-400">
          Editing
        </div>
      <% end %>

    </div>
    <div class="flex items-center gap-4">

      <% unless @workflow.activated? %>
        <%= link_to reset_workflow_path(@workflow) do %>
          <svg class="fill-current text-gray-300 hover:text-indigo-600 duration-100" xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 16.019 15.984">
            <path id="refresh_2" d="M362,709.012a1,1,0,0,0,1,1h4a1.006,1.006,0,0,0,1-1v-4a1,1,0,0,0-2,0v1.718a7.982,7.982,0,1,0,1.921,6.411,1,1,0,0,0-1-1.136,1,1,0,0,0-.984.857,6.016,6.016,0,1,1-1.48-4.853H363A1,1,0,0,0,362,709.012Z" transform="translate(-351.989 -704.017)"/>
          </svg>
        <% end %>
      <% end %>

      <% unless @workflow.activated? %>
        <%= link_to workflow_path(@workflow), method: 'DELETE' do %>
          <svg class="fill-current text-gray-300 mr-4 hover:text-indigo-600 duration-100" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
            <path id="delete_1" d="M47,547H43a3,3,0,0,0-6,0H33a1,1,0,0,0,0,2h1v9a2,2,0,0,0,2,2h8a2,2,0,0,0,2-2v-9h1a1,1,0,0,0,0-2Zm-7-1a1,1,0,0,1,1,1H39A1,1,0,0,1,40,546Zm4,12H36v-9h8Z" transform="translate(-32 -544)"/>
          </svg>
        <% end %>
      <% end %>
    </div>

  </div>
<% else %>
  <div class="h-12"></div>
<% end %>

app/views/workflows/_workflow_list.html.erb
<%= render partial: 'workflows/workflow_header' %>
<%# Workflow content %>

<div class="t-workflow-content flex-grow flex flex-col justify-between border rounded-lg">

  <div class="px-4 py-3 mb-5 bg-gray-100 text-xs text-gray-400 rounded-t-lg">
    Start
  </div>


  <% if @workflow %>
  <%# Content inside here %>
    <div class="flex-grow px-4">
      <div data-controller="task" data-workflow-id=<%= @workflow.id%> class="flex flex-col justify-center overflow-scroll">

        <div data-task-target="list">
        </div>

        <div data-task-target="newform">
        </div>
        <%= render "tasks/taskadd" %>
      </div>
    </div>
  <% end %>


  <div class="px-4 py-3 mt-5 bg-gray-100 text-xs text-gray-400 rounded-b-lg">
    End
  </div>

</div>

app/views/workflows/_workflow_status.html.erb
<div class="shadow-md rounded-md py-1 px-2 text-sm flex items-center" id="workflow-status">
  <% if @workflow.completed? %>
    <i class="fas fa-circle t-text-xs text-green-600"></i>
    &nbsp;Completed
  <% else %>
    <i class="fas fa-circle t-text-xs text-indigo-500"></i>
    &nbsp;Running
  <% end %>
</div>