config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/dashboard', to: "dashboard#index", as: :dashboard
  get '/current', to: 'dashboard#my_tasks', as: :current

  get '/workflows', to: 'workflows#search', as: :workflows

  resources :workflows, only: [:create, :show, :update, :destroy] do
    resources :tasks, only: [:index, :show]
    member do
      get :completion
      get :reset
    end
  end

  put '/activate', to: 'workflows#activate', as: :activate

  get '/tasks', to: 'tasks#search', as: :tasks

  resources :tasks, only: [:index, :new, :create, :destroy, :update] do
    resources :items, only: [:new]
    resources :task_members, only: [:create, :new, :destroy]
    member do
      get :complete_task
      get :complete_mytask
      get :show_mytask
    end
    get :email_notification, to: "notifications#email_notification"
  end

  resources :items, only: [:index, :create, :show, :destroy, :update] do
    member do
      patch :move
      patch :move_repo
      get :expand
      get :check
    end
  end



end

app/views/shared/_nav_account.html.erb
<div data-controller="account-dropdown">

  <button class="t-round-card p-2" data-action="click->account-dropdown#toggle">
    <div class="gap-2 flex items-center justify-between">

      <div class="flex-shrink-0 flex items-center gap-2 text-gray-700">
        <div class="t-no-profile <%= current_user.color %> text-white">
          <%= current_user.first_name.first.capitalize %><%= current_user.last_name.first.capitalize %>
        </div>
        <div class="text-sm">
          <%= current_user.first_name.capitalize %>&nbsp;<%= current_user.last_name.capitalize %>
        </div>
      </div>

      <div class="px-2" >
        <svg xmlns="http://www.w3.org/2000/svg" width="15.429" height="16" viewBox="0 0 15.429 16" class="fill-current text-gray-700">
          <path id="gear_2" d="M679,80a2,2,0,0,1-2-2l.021-.815-.72.415a2,2,0,0,1-2.741-.734l-1-1.741a2,2,0,0,1,.734-2.727l.708-.389-.708-.409a2,2,0,0,1-.734-2.728l1-1.741a2.009,2.009,0,0,1,1.217-.935,2.048,2.048,0,0,1,.52-.067,2,2,0,0,1,1,.269l.7.427V66a2,2,0,0,1,2-2h2a2,2,0,0,1,2,2l-.02.814.72-.415a2,2,0,0,1,1-.269,2.041,2.041,0,0,1,.519.067,2.015,2.015,0,0,1,1.219.935l1,1.741a2,2,0,0,1-.734,2.728l-.722.38.722.418a2,2,0,0,1,.734,2.727l-1,1.741a2.006,2.006,0,0,1-2.741.734l-.7-.427V78a2,2,0,0,1-2,2Zm-1.016-4.543.029.017a1.962,1.962,0,0,1,.987,1.7V78h2v-.826a1.959,1.959,0,0,1,.987-1.7l.029-.017a1.97,1.97,0,0,1,1.971,0l.72.416,1-1.74-.723-.418a1.956,1.956,0,0,1-.98-1.7v-.023a1.959,1.959,0,0,1,.98-1.7l.723-.418-1-1.74-.72.416a1.97,1.97,0,0,1-1.971,0l-.029-.017a1.962,1.962,0,0,1-.987-1.7V66h-2v.826a1.958,1.958,0,0,1-.988,1.7l-.028.017a1.97,1.97,0,0,1-1.971,0l-.72-.416-1,1.74.709.41a1.987,1.987,0,0,1,0,3.442l-.709.41,1,1.74.72-.416a1.97,1.97,0,0,1,1.971,0ZM678,72a2,2,0,1,1,2,2A2,2,0,0,1,678,72Z" transform="translate(-672.284 -64)"/>
        </svg>
      </div>

    </div>
  </button>


  <div class="t-dropdown w-44 hidden" data-account-dropdown-target="menu">
    <%= link_to "Your profile", edit_user_registration_path, class:"t-dropdown-btn" %>
    <a href="#" class="t-dropdown-btn">
      Your projects
    </a>
    <a href="#" class="t-dropdown-btn">
      Help
    </a>
    <a href="#" class="t-dropdown-btn">
      Settings
    </a>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"t-dropdown-btn" %>
  </div>

</div>

app/views/shared/_sidebar_l.html.erb
<div data-controller="sidebar-l">

  <%# create button %>
  <button data-action="click->sidebar-l#createBtnDropdown" class="t-btn-outline mt-5">
      <svg class="t-hover-white mx-2" xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10">
        <path id="mini_plus" d="M44,743H41v-3a1,1,0,0,0-2,0v3H36a1,1,0,0,0,0,2h3v3a1,1,0,0,0,2,0v-3h3a1,1,0,0,0,0-2Z" transform="translate(-35 -739)"/>
      </svg>
    <h5 class="text-sm">Create</h5>
  </button>

  <%# create button dropdown %>
  <div data-sidebar-l-target="dropdownCreate" class="t-dropdown w-48 hidden">
    <%= link_to 'Workflow', workflows_path, method: 'post',
    class: "t-dropdown-btn" %>
  </div>

  <%# nav tab %>
  <div class="flex gap-4 my-5">
    <%= link_to "My Tasks #{ "(#{current_user.my_tasks.length})" unless current_user.my_tasks.empty?}", current_path, class: 't-tab' %>
    <%= link_to 'Workflows', dashboard_path, class: 't-tab-active' %>
  </div>

  <%# search bar form to search within tab %>
  <%= form_with url: workflows_path, class: "text-light", method: :get do |f| %>

    <div class="search-bar rounded-t-lg">
      <button type="submit" class="input-l">
        <i class="fas fa-search"></i>
      </button>

      <%= f.text_field :query, class: "t-input-invis flex-grow pl-3 bg-gray-700", placeholder: "Workflows" %>
    </div>

  <% end %>

  <%# workflows tabs list %>
  <%= render 'shared/workflows_tabs', workflows: @workflows %>

</div>

app/views/shared/_sidebar_r.html.erb
<%= render 'shared/nav_account' %>

<div class="fixed w-64">

  <div class="py-2 px-2 mt-8">
    <h3 class="text-lg font-medium text-gray-600">Saved items</h3>
  </div>

  <div class="px-2 py-4 t-card border">
    <div class="bg-gray-100 rounded-lg overflow-scroll h-96 shadow-inner">
      <ul class="t-item-box h-full rounded-lg px-2 pb-1" data-controller="drag" data-drag-url="/items/:id/move_repo">

        <div class="text-xs text-gray-300 text-center pt-2">Drop items here</div>

        <% current_user.items.each do |item| %>
          <%= render partial: 'items/taskless_item', locals: { item: item } %>
        <% end %>

      </ul>
    </div>
  </div>

</div>

app/views/shared/_workflow_tab.html.erb
<%# FOR AJAX ONLY %>
<div class="t-workflow-btn-active">
  <%= link_to workflow.title, workflow_path(workflow), id: 'workflow', remote: true %>
</div>

app/views/shared/_workflows_list.html copy.erb
<% workflows.each do |workflow| %>

  <div class="flex pb-2" data-controller="workflow">
    <label for="toggleButton" class="flex items-center justify-between w-full cursor-pointer">

      <div class="px-2 text-sm"><%= workflow.title %></div>

      <!-- toggle -->
      <div class="relative">
        <input id="toggleButton" type="checkbox" class="hidden" data-workflow-target="activated"/>
        <!-- path -->
        <div
          class="toggle-path bg-gray-200 w-9 h-5 rounded-full shadow-inner"
        ></div>
        <!-- crcle -->
        <div
          class="toggle-circle absolute w-3.5 h-3.5 bg-white rounded-full shadow inset-y-.5 left-.5"
        ></div>
      </div>
    </label>
  </div>

<% end %>

app/views/shared/_workflows_tabs.html.erb
<div id="workflow-tabs" class="mt-4 h-96 overflow-scroll">
  <% workflows.each do |workflow| %>

    <% if workflow == @workflow %>
      <div data-workflow-id=<%= workflow.id %> data-controller="sidetabs" class="t-sidetab-btn-active flex items-center justify-between">
    <% else %>
      <div data-workflow-id=<%= workflow.id %> data-controller="sidetabs" class="t-sidetab-btn flex items-center justify-between">
    <% end %>

      <%= link_to workflow_path(workflow), class: "flex-grow flex items-center gap-2" do %>
        <div class="mr-2">
          <svg class="<%= "animate-bounce fill-current text-green-400" if workflow.completed? %>" xmlns="http://www.w3.org/2000/svg" width="14" height="12" viewBox="0 0 16 14">
            <path id="folder_1" d="M334,451h-4.764l-.447-.895A2,2,0,0,0,327,449h-5a2,2,0,0,0-2,2v10a2,2,0,0,0,2,2h12a2,2,0,0,0,2-2v-8A2,2,0,0,0,334,451Zm-7,0,1,2h6v1H324a1,1,0,0,0-.949.683L322,457.837V451Zm7,10H323.054l1.667-5H334Z" transform="translate(-320 -449)"/>
          </svg>
        </div>
        <%= workflow.title %>
      <% end %>

      <label for="toggleBtn<%= workflow.id %>" data-action="change->sidetabs#activateWorkflowToggle" class="cursor-pointer">
        <!-- toggle -->
        <div class="relative">
          <% if workflow.activated? %>
            <input id="toggleBtn<%= workflow.id %>" type="checkbox" class="hidden" checked="true">
          <% else %>
            <input id="toggleBtn<%= workflow.id %>" type="checkbox" class="hidden">
          <% end %>
          <div class="toggle-path bg-gray-800 w-9 h-5 rounded-full shadow-inner"></div>
          <div class="toggle-circle absolute w-3.5 h-3.5 bg-white rounded-full shadow inset-y-.5 left-.5"></div>
        </div>
      </label>
    </div>

  <% end %>
</div>